Repository cdelriot1121/Spring.ClassroomProject-SERVIAPP, pull requests merged in 2025-05, with the labels that each got.

#74 Corrección de Errores en Cortes y Gestionar Servicios Administrador, Tambien mas Front
  src/main/java/com/example/ServiApp/controller/AdminController.java
  src/main/java/com/example/ServiApp/controller/CortesController.java
  src/main/java/com/example/ServiApp/services/UsuarioService.java
  src/main/resources/static/estilos_interfaz-usuario/interfaz_inicio.css
  src/main/resources/static/estilos_interfaz-usuario/style_gest_ser.css
  src/main/resources/static/estilos_interfaz-usuario/style_reg_servicio.css
  src/main/resources/templates/cortes_fallas.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/grafico_consumo.html
  src/main/resources/templates/interfaz_inicio.html
  src/main/resources/templates/reg_servicio.html
  src/main/resources/templates/reportes_admin.html
Labels: enhancement, Task Completed

#75 Integracion de Base de Datos Redis y tambien mecanicas SMTP en el registro de usuarios
  docker-compose.yml
  pom.xml
  src/main/java/com/example/ServiApp/config/CustomOAuth2User.java
  src/main/java/com/example/ServiApp/config/RedisSessionConfig.java
  src/main/java/com/example/ServiApp/config/SecurityConfiguration.java
  src/main/java/com/example/ServiApp/controller/OtpController.java
  src/main/java/com/example/ServiApp/controller/UsuarioController.java
  src/main/java/com/example/ServiApp/model/PredioModel.java
  src/main/java/com/example/ServiApp/model/ServicioModel.java
  src/main/java/com/example/ServiApp/model/UsuarioModel.java
  src/main/java/com/example/ServiApp/services/OtpService.java
  src/main/java/com/example/ServiApp/services/UsuarioService.java
  src/main/resources/application.properties
  src/main/resources/static/estilos_inicio/registro.css
  src/main/resources/static/javascripts/mensaje_registro_exitoso.js
  src/main/resources/static/javascripts/ojito_password.js
  src/main/resources/templates/registro_usuario.html
Labels: enhancement, Migration, Task Completed

#76 Mongo contexto
  src/main/java/com/example/ServiApp/config/SecurityConfiguration.java
  src/main/java/com/example/ServiApp/controller/CortesController.java
  src/main/java/com/example/ServiApp/controller/FallasUserController.java
  src/main/java/com/example/ServiApp/controller/ServicioController.java
  src/main/java/com/example/ServiApp/model/Falla_Ser_Model.java
  src/main/java/com/example/ServiApp/services/FallasUserService.java
  src/main/java/com/example/ServiApp/services/OtpService.java
  src/main/java/com/example/ServiApp/util/passworGenerator.java
  src/main/resources/application.properties
  src/main/resources/static/estilos_interfaz-usuario/style_gest_ser.css
  src/main/resources/static/estilos_interfaz-usuario/style_perfil.css
  src/main/resources/static/javascripts/Js_GestionServiciosAdmin.js
  src/main/resources/templates/ReportesUserAdmin.html
  src/main/resources/templates/consejos_personalizados.html
  src/main/resources/templates/cortes_fallas.html
  src/main/resources/templates/ges-servicios-admin.html
  src/main/resources/templates/otp-email.html
  src/main/resources/templates/perfil_datos.html
Labels: Task Completed

#77 Cambios en las paginas de inicio del front y Cambios Cortes de Willys
  .dockerignore
  Dockerfile
  pom.xml
  src/main/java/com/example/ServiApp/controller/CortesController.java
  src/main/java/com/example/ServiApp/controller/RegistroPredioObligatorioController.java
  src/main/java/com/example/ServiApp/services/CortesService.java
  src/main/resources/application.properties
  src/main/resources/static/estilos_inicio/acerca_del_proyecto.css
  src/main/resources/static/estilos_inicio/style_consejos.css
  src/main/resources/static/javascripts/TablaServiciosAdmin.js
  src/main/resources/static/javascripts/consejos.js
  src/main/resources/templates/acerca_del_proyecto.html
  src/main/resources/templates/consejos_ahorro.html
  src/main/resources/templates/cortes_fallas.html
  src/main/resources/templates/ges-servicios-admin.html
  src/main/resources/templates/registrar_predio_obligatorio.html
  src/main/resources/templates/reportes_admin.html
Labels: enhancement, Task Completed

#78 Ajustes Front paginas principales SERVIAPP
  src/main/java/com/example/ServiApp/controller/PeriodoController.java
  src/main/java/com/example/ServiApp/controller/PredioController.java
  src/main/resources/static/estilos_inicio/acerca_del_proyecto.css
  src/main/resources/static/estilos_inicio/style_consejos.css
  src/main/resources/static/javascripts/sweet-alerts-handlers.js
  src/main/resources/templates/acerca_del_proyecto.html
  src/main/resources/templates/consejos_ahorro.html
  src/main/resources/templates/perfil_datos.html
Labels: enhancement, Task Completed

#87 Aplicar Cambios de Correcciones Gaos
  src/main/java/com/example/ServiApp/controller/AdminController.java
  src/main/java/com/example/ServiApp/services/FallasUserService.java
  src/main/resources/static/javascripts/TablaUsuariosAdmin.js
  src/main/resources/templates/ReportesUserAdmin.html
  src/main/resources/templates/interfaz-admin.html
  src/main/resources/templates/perfil_datos.html
Labels: enhancement, Migration

#88 Manejo del Scroll para ver los resultados y rompiendo limites de los periodos
  src/main/java/com/example/ServiApp/controller/PeriodoController.java
  src/main/resources/templates/gestionar_serv.html
Labels: Migration, Task Completed
